### ISSUE TITLE
cabal run not available everywhere

### ISSUE THREAD

**Issue by gohai** [samplecount/methcla#108]
Running `./shake desktop` fails for me with `cabal: unrecognised command: run (try --help)`. And indeed, the run verb doesn't show up on `cabal --help`. (This is on current Raspbian with ghc-7.4.1.)

```
pi@raspberrypi ~/methcla $ cabal -V
cabal-install version 0.14.0
using version 1.14.0 of the Cabal library
```

**Comment by kaoskorobase** [comment]
We currently only support the latest Haskell platform and GHC >= 7.8. You could try installing a newer version of cabal-install (`cabal install cabal-install`) by hand, but I'm not sure with which version exactly the `run` command was introduced.
